### ISSUE TITLE
NPM ERROR Installing dependencies!

### ISSUE THREAD

**Issue by MKS2508** [Jantje19/MusicStream#4]
Hi, I really like your project, but when I try to install dependencies npm throws an error related to musicstream-installer.
Could you check this please? Thanks!
<img width="687" alt="image" src="https://user-images.githubusercontent.com/60777608/150109270-4cba96d3-d414-4bff-9b31-f7943075ad44.png">

**Comment by Jantje19** [comment]
Thank you, I removed this package a while back. It should be fixed now (838ed0ad490f455c849a04521de38ec3bc0bd2c6)
